dotnet add ETL/ETL.API package Microsoft.EntityFrameworkCore.SqlServer
dotnet add ETL/ETL.API package Microsoft.EntityFrameworkCore.Design
dotnet add ETL/ETL.API package Microsoft.EntityFrameworkCore.Tools
dotnet add ETL/ETL.API package Microsoft.AspNetCore.Authentication.JwtBearer
dotnet add ETL/ETL.API package Microsoft.AspNetCore.Identity.EntityFrameworkCore
dotnet add ETL/ETL.API package Serilog.AspNetCore
dotnet add ETL/ETL.API package Serilog.Sinks.Console
dotnet add ETL/ETL.API package Serilog.Sinks.MSSqlServer
dotnet add ETL/ETL.Application package MediatR
dotnet add ETL/ETL.Application package FluentValidation
dotnet add ETL/ETL.Application package AutoMapper
dotnet add ETL/ETL.Infrastructure package Hangfire
dotnet add ETL/ETL.Infrastructure package Hangfire.SqlServer
dotnet add ETL/ETL.Tests package xunit
dotnet add ETL/ETL.Tests package Moq